//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Layout", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затвердити.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати елемент.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий навчальний елемент.
        /// </summary>
        internal static string add_edu_elem {
            get {
                return ResourceManager.GetString("add_edu_elem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адмін-панель.
        /// </summary>
        internal static string admin_panel {
            get {
                return ResourceManager.GetString("admin_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі курси.
        /// </summary>
        internal static string all_courses {
            get {
                return ResourceManager.GetString("all_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to та.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В початок сторінки.
        /// </summary>
        internal static string App_Footer_TopPage {
            get {
                return ResourceManager.GetString("App_Footer_TopPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На головну сторінку.
        /// </summary>
        internal static string App_HomePage {
            get {
                return ResourceManager.GetString("App_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примітка:.
        /// </summary>
        internal static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії предметів.
        /// </summary>
        internal static string categories_courses {
            get {
                return ResourceManager.GetString("categories_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія:.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс:.
        /// </summary>
        internal static string course {
            get {
                return ResourceManager.GetString("course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курси.
        /// </summary>
        internal static string courses {
            get {
                return ResourceManager.GetString("courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поки що немає категорій..
        /// </summary>
        internal static string data_null_category {
            get {
                return ResourceManager.GetString("data_null_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактні дані не вказано.
        /// </summary>
        internal static string data_null_cd {
            get {
                return ResourceManager.GetString("data_null_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсів поки що не створено. Очікуйте..
        /// </summary>
        internal static string data_null_courses {
            get {
                return ResourceManager.GetString("data_null_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ніхто не проходив тестування з цього предмету.
        /// </summary>
        internal static string data_null_detail_course {
            get {
                return ResourceManager.GetString("data_null_detail_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ніхто не проходив тестування з цього модуля.
        /// </summary>
        internal static string data_null_detail_module {
            get {
                return ResourceManager.GetString("data_null_detail_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список повідомлень пустий..
        /// </summary>
        internal static string data_null_message {
            get {
                return ResourceManager.GetString("data_null_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нових повідомлень немає..
        /// </summary>
        internal static string data_null_newmessage {
            get {
                return ResourceManager.GetString("data_null_newmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поки що немає ніяких новин..
        /// </summary>
        internal static string data_null_news {
            get {
                return ResourceManager.GetString("data_null_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особисті дані не вказано.
        /// </summary>
        internal static string data_null_pd {
            get {
                return ResourceManager.GetString("data_null_pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша залікова книжка поки що пуста..
        /// </summary>
        internal static string data_null_student_result {
            get {
                return ResourceManager.GetString("data_null_student_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає підписок на курси..
        /// </summary>
        internal static string data_null_subscribs {
            get {
                return ResourceManager.GetString("data_null_subscribs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тести не створені.
        /// </summary>
        internal static string data_null_test {
            get {
                return ResourceManager.GetString("data_null_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не проходив тестування з цього предмету.
        /// </summary>
        internal static string data_null_testing {
            get {
                return ResourceManager.GetString("data_null_testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жодного тестування не пройдено.
        /// </summary>
        internal static string data_null_testing2 {
            get {
                return ResourceManager.GetString("data_null_testing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата:.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути.
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальніше:.
        /// </summary>
        internal static string detailing {
            get {
                return ResourceManager.GetString("detailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навчання.
        /// </summary>
        internal static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навчальні елементи модуля.
        /// </summary>
        internal static string edu_elements {
            get {
                return ResourceManager.GetString("edu_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шукати.
        /// </summary>
        internal static string go_search {
            get {
                return ResourceManager.GetString("go_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to год..
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наш сайт не підтримує ваш браузер.\nДля корректної роботи, встановіть інший браузер.\nНаприклад: Google Chrome(рекомендуємо), Opera, Mozilla Firefox, Safari, etc...\n\nВибачте за будь-які можливі незручності ;).
        /// </summary>
        internal static string ie_error {
            get {
                return ResourceManager.GetString("ie_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал успішності.
        /// </summary>
        internal static string journal {
            get {
                return ResourceManager.GetString("journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекція.
        /// </summary>
        internal static string lesson {
            get {
                return ResourceManager.GetString("lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.
        /// </summary>
        internal static string local_short {
            get {
                return ResourceManager.GetString("local_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню навчання.
        /// </summary>
        internal static string menu_education {
            get {
                return ResourceManager.GetString("menu_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Підтверджено].
        /// </summary>
        internal static string mes_confirmed {
            get {
                return ResourceManager.GetString("mes_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Від кого:.
        /// </summary>
        internal static string mes_from {
            get {
                return ResourceManager.GetString("mes_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення:.
        /// </summary>
        internal static string mes_message {
            get {
                return ResourceManager.GetString("mes_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написати нове повідомлення.
        /// </summary>
        internal static string mes_new {
            get {
                return ResourceManager.GetString("mes_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Не прочитане].
        /// </summary>
        internal static string mes_not_read {
            get {
                return ResourceManager.GetString("mes_not_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особисті повідомлення:.
        /// </summary>
        internal static string mes_private_messages {
            get {
                return ResourceManager.GetString("mes_private_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Відмовлено].
        /// </summary>
        internal static string mes_rejected {
            get {
                return ResourceManager.GetString("mes_rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому:.
        /// </summary>
        internal static string mes_to {
            get {
                return ResourceManager.GetString("mes_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема:.
        /// </summary>
        internal static string mes_topic {
            get {
                return ResourceManager.GetString("mes_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коли:.
        /// </summary>
        internal static string mes_when {
            get {
                return ResourceManager.GetString("mes_when", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написати повідомлення.
        /// </summary>
        internal static string mes_write_message {
            get {
                return ResourceManager.GetString("mes_write_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to хв..
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль:.
        /// </summary>
        internal static string module {
            get {
                return ResourceManager.GetString("module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модулі:.
        /// </summary>
        internal static string modules {
            get {
                return ResourceManager.GetString("modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої предмети.
        /// </summary>
        internal static string my_courses {
            get {
                return ResourceManager.GetString("my_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя залікова книжка.
        /// </summary>
        internal static string my_record_book {
            get {
                return ResourceManager.GetString("my_record_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої підписки.
        /// </summary>
        internal static string my_subscriptions {
            get {
                return ResourceManager.GetString("my_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далі.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка не знайдена.
        /// </summary>
        internal static string page_not_found {
            get {
                return ResourceManager.GetString("page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чому виникає така помилка?.
        /// </summary>
        internal static string page_not_found_question {
            get {
                return ResourceManager.GetString("page_not_found_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;-Можливо, у вас немає права доступу до сторінки&lt;/p&gt;
        ///        &lt;p&gt;-Можливо, сторінки, до якої Ви звертаєтесь - не існує&lt;/p&gt;
        ///        &lt;p&gt;-Можливо, на сервері ведуться роботи і сторінка тимчасово не доступна&lt;/p&gt;.
        /// </summary>
        internal static string page_not_found_theory {
            get {
                return ResourceManager.GetString("page_not_found_theory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;-Перевірте введені дані&lt;/p&gt;
        ///        &lt;p&gt;-Спробуйте ще раз звернутись до потрібної Вам адреси&lt;/p&gt;
        ///        &lt;p&gt;-Зверніться до адміністрації, якщо Ви впевнені що сторінка, до якої ви звертаїтесь - існує&lt;/p&gt;.
        /// </summary>
        internal static string page_not_found_theory2 {
            get {
                return ResourceManager.GetString("page_not_found_theory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінки по вашому запиту не знайдено.
        /// </summary>
        internal static string page_not_found_title {
            get {
                return ResourceManager.GetString("page_not_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можливі шляхи вирішення проблеми.
        /// </summary>
        internal static string page_not_found_try {
            get {
                return ResourceManager.GetString("page_not_found_try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватні.
        /// </summary>
        internal static string private_courses {
            get {
                return ResourceManager.GetString("private_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальнодоступні.
        /// </summary>
        internal static string public_courses {
            get {
                return ResourceManager.GetString("public_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to запитання.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читати.
        /// </summary>
        internal static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль:.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалось зберегти результати. Виправте помилки і спробуйте ще раз..
        /// </summary>
        internal static string save_error {
            get {
                return ResourceManager.GetString("save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук користувача.
        /// </summary>
        internal static string search_for_users {
            get {
                return ResourceManager.GetString("search_for_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук лекції.
        /// </summary>
        internal static string search_the_lesson {
            get {
                return ResourceManager.GetString("search_the_lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук предмету.
        /// </summary>
        internal static string search_the_subject {
            get {
                return ResourceManager.GetString("search_the_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сек..
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправити.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти на сторінку.
        /// </summary>
        internal static string Slider_ToPage {
            get {
                return ResourceManager.GetString("Slider_ToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to реєстрації.
        /// </summary>
        internal static string Slider_ToRegister {
            get {
                return ResourceManager.GetString("Slider_ToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розпочати тестування.
        /// </summary>
        internal static string start_test {
            get {
                return ResourceManager.GetString("start_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус:.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватний.
        /// </summary>
        internal static string stat_private {
            get {
                return ResourceManager.GetString("stat_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей курс є приватним. Очікуйте затвердження підписки від викладача та оповіщення в особистих повідомленнях..
        /// </summary>
        internal static string stat_private_alert_subscrb {
            get {
                return ResourceManager.GetString("stat_private_alert_subscrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальнодоступний.
        /// </summary>
        internal static string stat_public {
            get {
                return ResourceManager.GetString("stat_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви підписались на курс!\n\rПро терміни здачі модуля Ви будете оповіщені по системі особистих повідомлень.\n\r\n\rЩоб відмінити підписку натисніть &quot;Відмінити&quot;.
        /// </summary>
        internal static string stat_public_alert_subscrb {
            get {
                return ResourceManager.GetString("stat_public_alert_subscrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підписатись.
        /// </summary>
        internal static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач:.
        /// </summary>
        internal static string teacher {
            get {
                return ResourceManager.GetString("teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладацька.
        /// </summary>
        internal static string teacher_panel {
            get {
                return ResourceManager.GetString("teacher_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тести.
        /// </summary>
        internal static string tests {
            get {
                return ResourceManager.GetString("tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити.
        /// </summary>
        internal static string upld {
            get {
                return ResourceManager.GetString("upld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження навчального елементу.
        /// </summary>
        internal static string upload_edu_elem {
            get {
                return ResourceManager.GetString("upload_edu_elem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка завантаження.
        /// </summary>
        internal static string upload_error {
            get {
                return ResourceManager.GetString("upload_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальний розмір завантажувального файлу - 5 Мб..
        /// </summary>
        internal static string upload_info1 {
            get {
                return ResourceManager.GetString("upload_info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимі розширення - .pdf, .doc, .docx, .rtf, .txt, .htm, .html, .mhtml, .xhtml,
        ///    .jpg, .jpeg, .bmp!.
        /// </summary>
        internal static string upload_info2 {
            get {
                return ResourceManager.GetString("upload_info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторити завантаження.
        /// </summary>
        internal static string upload_retry {
            get {
                return ResourceManager.GetString("upload_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачі.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очікуємо підтвердження.
        /// </summary>
        internal static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення категорії.
        /// </summary>
        internal static string _category_create {
            get {
                return ResourceManager.GetString("_category_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування категорії.
        /// </summary>
        internal static string _category_edit {
            get {
                return ResourceManager.GetString("_category_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення предмету.
        /// </summary>
        internal static string _course_create {
            get {
                return ResourceManager.GetString("_course_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування предмету.
        /// </summary>
        internal static string _course_edit {
            get {
                return ResourceManager.GetString("_course_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекції, що не належать до модуля.
        /// </summary>
        internal static string _course_null_module {
            get {
                return ResourceManager.GetString("_course_null_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмети.
        /// </summary>
        internal static string _HorizontalNavigation_Courses {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навчання.
        /// </summary>
        internal static string _HorizontalNavigation_Education {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        internal static string _HorizontalNavigation_HomePage {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        internal static string _HorizontalNavigation_News {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль.
        /// </summary>
        internal static string _HorizontalNavigation_Profile {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про дану лекцію.
        /// </summary>
        internal static string _lesson_about {
            get {
                return ResourceManager.GetString("_lesson_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавити лекцію.
        /// </summary>
        internal static string _lesson_add {
            get {
                return ResourceManager.GetString("_lesson_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити джерело лекції.
        /// </summary>
        internal static string _lesson_change_url {
            get {
                return ResourceManager.GetString("_lesson_change_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування лекції.
        /// </summary>
        internal static string _lesson_edit {
            get {
                return ResourceManager.GetString("_lesson_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помістити лекцію за межі модулів.
        /// </summary>
        internal static string _lesson_to_null_module {
            get {
                return ResourceManager.GetString("_lesson_to_null_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Джерело лекції.
        /// </summary>
        internal static string _lesson_url {
            get {
                return ResourceManager.GetString("_lesson_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        internal static string _LogOnPartial_Exit {
            get {
                return ResourceManager.GetString("_LogOnPartial_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привіт,.
        /// </summary>
        internal static string _LogOnPartial_Hello {
            get {
                return ResourceManager.GetString("_LogOnPartial_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string _LogOnPartial_Register {
            get {
                return ResourceManager.GetString("_LogOnPartial_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Війти.
        /// </summary>
        internal static string _LogOnPartial_SignIn {
            get {
                return ResourceManager.GetString("_LogOnPartial_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про модуль.
        /// </summary>
        internal static string _module_about {
            get {
                return ResourceManager.GetString("_module_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити модуль.
        /// </summary>
        internal static string _module_create {
            get {
                return ResourceManager.GetString("_module_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення модулю.
        /// </summary>
        internal static string _module_creating {
            get {
                return ResourceManager.GetString("_module_creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування модулю.
        /// </summary>
        internal static string _module_edit {
            get {
                return ResourceManager.GetString("_module_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здача модуля.
        /// </summary>
        internal static string _module_passing {
            get {
                return ResourceManager.GetString("_module_passing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата початку здачі модуля має бути меншою дати закінчення!.
        /// </summary>
        internal static string _module_time_invalid {
            get {
                return ResourceManager.GetString("_module_time_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нових повідомлень: .
        /// </summary>
        internal static string _NewMessageBox_NewMesseges {
            get {
                return ResourceManager.GetString("_NewMessageBox_NewMesseges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При вказуванні дати народження - будьте обачні. Після задання дати народження, її вже не можна буде змінити..
        /// </summary>
        internal static string _profile_attention_dob {
            get {
                return ResourceManager.GetString("_profile_attention_dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У випадку, якщо Ви захочете заповнити особисті дані: поля, що відмічені.
        /// </summary>
        internal static string _profile_attention_required_1 {
            get {
                return ResourceManager.GetString("_profile_attention_required_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - є обовязкові..
        /// </summary>
        internal static string _profile_attention_required_2 {
            get {
                return ResourceManager.GetString("_profile_attention_required_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактні дані.
        /// </summary>
        internal static string _profile_cd {
            get {
                return ResourceManager.GetString("_profile_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування контактних даних.
        /// </summary>
        internal static string _profile_edit_cd {
            get {
                return ResourceManager.GetString("_profile_edit_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування особистих даних.
        /// </summary>
        internal static string _profile_edit_pd {
            get {
                return ResourceManager.GetString("_profile_edit_pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особиста інформація.
        /// </summary>
        internal static string _profile_pd {
            get {
                return ResourceManager.GetString("_profile_pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрування в базі контактних даних.
        /// </summary>
        internal static string _profile_register_in_db_cd {
            get {
                return ResourceManager.GetString("_profile_register_in_db_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрування в базі даних особистої інформації.
        /// </summary>
        internal static string _profile_register_in_db_pd {
            get {
                return ResourceManager.GetString("_profile_register_in_db_pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль користувача.
        /// </summary>
        internal static string _profile_user {
            get {
                return ResourceManager.GetString("_profile_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль користувача -.
        /// </summary>
        internal static string _profile_username {
            get {
                return ResourceManager.GetString("_profile_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш профіль.
        /// </summary>
        internal static string _profile_your {
            get {
                return ResourceManager.GetString("_profile_your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернутись до результатів модуля.
        /// </summary>
        internal static string _result_back_to_result {
            get {
                return ResourceManager.GetString("_result_back_to_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Початок тестування.
        /// </summary>
        internal static string _result_begin_test {
            get {
                return ResourceManager.GetString("_result_begin_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здані модулі.
        /// </summary>
        internal static string _result_complete_module {
            get {
                return ResourceManager.GetString("_result_complete_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат курсу.
        /// </summary>
        internal static string _result_course {
            get {
                return ResourceManager.GetString("_result_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінка за курс.
        /// </summary>
        internal static string _result_courses_points {
            get {
                return ResourceManager.GetString("_result_courses_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі тестування.
        /// </summary>
        internal static string _result_detail_testing {
            get {
                return ResourceManager.GetString("_result_detail_testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здає тест.
        /// </summary>
        internal static string _result_in_action {
            get {
                return ResourceManager.GetString("_result_in_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін та ініціали користувача.
        /// </summary>
        internal static string _result_loginPIP {
            get {
                return ResourceManager.GetString("_result_loginPIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результати модулів.
        /// </summary>
        internal static string _result_modules {
            get {
                return ResourceManager.GetString("_result_modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат тестування з модуля.
        /// </summary>
        internal static string _result_module_result {
            get {
                return ResourceManager.GetString("_result_module_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає відповіді.
        /// </summary>
        internal static string _result_null_answer {
            get {
                return ResourceManager.GetString("_result_null_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додаткові дії.
        /// </summary>
        internal static string _result_other_action {
            get {
                return ResourceManager.GetString("_result_other_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онулити результат тестування.
        /// </summary>
        internal static string _result_refresh_result {
            get {
                return ResourceManager.GetString("_result_refresh_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат.
        /// </summary>
        internal static string _result_result {
            get {
                return ResourceManager.GetString("_result_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат здачі модуля.
        /// </summary>
        internal static string _result_result_title {
            get {
                return ResourceManager.GetString("_result_result_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to користувачем.
        /// </summary>
        internal static string _result_result_title2 {
            get {
                return ResourceManager.GetString("_result_result_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to балів.
        /// </summary>
        internal static string _result_result_title3 {
            get {
                return ResourceManager.GetString("_result_result_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        internal static string _result_test {
            get {
                return ResourceManager.GetString("_result_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповідь користувача.
        /// </summary>
        internal static string _result_user_answer {
            get {
                return ResourceManager.GetString("_result_user_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бали користувача.
        /// </summary>
        internal static string _result_user_points {
            get {
                return ResourceManager.GetString("_result_user_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна інформація.
        /// </summary>
        internal static string _summary_info {
            get {
                return ResourceManager.GetString("_summary_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування тестів.
        /// </summary>
        internal static string _tests_edit {
            get {
                return ResourceManager.GetString("_tests_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування тестів.
        /// </summary>
        internal static string _test_editing {
            get {
                return ResourceManager.GetString("_test_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація користувача.
        /// </summary>
        internal static string _test_edit_legend {
            get {
                return ResourceManager.GetString("_test_edit_legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишилось часу.
        /// </summary>
        internal static string _test_have_time {
            get {
                return ResourceManager.GetString("_test_have_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестування з модуля.
        /// </summary>
        internal static string _test_not_prepared {
            get {
                return ResourceManager.GetString("_test_not_prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не можливе. Зверніться до викладача за деталями.
        /// </summary>
        internal static string _test_not_prepared2 {
            get {
                return ResourceManager.GetString("_test_not_prepared2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестування з модуля.
        /// </summary>
        internal static string _test_not_testing {
            get {
                return ResourceManager.GetString("_test_not_testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не проводиться..
        /// </summary>
        internal static string _test_not_testing2 {
            get {
                return ResourceManager.GetString("_test_not_testing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останній вказаний час з.
        /// </summary>
        internal static string _test_not_testing3 {
            get {
                return ResourceManager.GetString("_test_not_testing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результати тестування.
        /// </summary>
        internal static string _test_result {
            get {
                return ResourceManager.GetString("_test_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш результат тестування з модуля.
        /// </summary>
        internal static string _test_result_say {
            get {
                return ResourceManager.GetString("_test_result_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі тести з модуля.
        /// </summary>
        internal static string _test_showmodtests {
            get {
                return ResourceManager.GetString("_test_showmodtests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестування складається з.
        /// </summary>
        internal static string _test_showmodtests2 {
            get {
                return ResourceManager.GetString("_test_showmodtests2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to запитань на які відведено.
        /// </summary>
        internal static string _test_showmodtests3 {
            get {
                return ResourceManager.GetString("_test_showmodtests3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стиль:.
        /// </summary>
        internal static string _theme {
            get {
                return ResourceManager.GetString("_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синій.
        /// </summary>
        internal static string _theme_blue {
            get {
                return ResourceManager.GetString("_theme_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помаранчовий.
        /// </summary>
        internal static string _theme_orange {
            get {
                return ResourceManager.GetString("_theme_orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення користувача.
        /// </summary>
        internal static string _user_create {
            get {
                return ResourceManager.GetString("_user_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати користувача.
        /// </summary>
        internal static string _user_edit {
            get {
                return ResourceManager.GetString("_user_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про користувача.
        /// </summary>
        internal static string _user_info {
            get {
                return ResourceManager.GetString("_user_info", resourceCulture);
            }
        }
    }
}
