//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Layout", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі курси.
        /// </summary>
        internal static string all_courses {
            get {
                return ResourceManager.GetString("all_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В початок сторінки.
        /// </summary>
        internal static string App_Footer_TopPage {
            get {
                return ResourceManager.GetString("App_Footer_TopPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На головну сторінку.
        /// </summary>
        internal static string App_HomePage {
            get {
                return ResourceManager.GetString("App_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія:.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курси.
        /// </summary>
        internal static string courses {
            get {
                return ResourceManager.GetString("courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поки що немає категорій..
        /// </summary>
        internal static string data_null_category {
            get {
                return ResourceManager.GetString("data_null_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсів поки що не створено. Очікуйте..
        /// </summary>
        internal static string data_null_courses {
            get {
                return ResourceManager.GetString("data_null_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає підписок на курси..
        /// </summary>
        internal static string data_null_subscribs {
            get {
                return ResourceManager.GetString("data_null_subscribs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шукати.
        /// </summary>
        internal static string go_search {
            get {
                return ResourceManager.GetString("go_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню навчання.
        /// </summary>
        internal static string menu_education {
            get {
                return ResourceManager.GetString("menu_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль:.
        /// </summary>
        internal static string module {
            get {
                return ResourceManager.GetString("module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя залікова книжка.
        /// </summary>
        internal static string my_record_book {
            get {
                return ResourceManager.GetString("my_record_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої підписки.
        /// </summary>
        internal static string my_subscriptions {
            get {
                return ResourceManager.GetString("my_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватні.
        /// </summary>
        internal static string private_courses {
            get {
                return ResourceManager.GetString("private_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальнодоступні.
        /// </summary>
        internal static string public_courses {
            get {
                return ResourceManager.GetString("public_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читати.
        /// </summary>
        internal static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук користувача.
        /// </summary>
        internal static string search_for_users {
            get {
                return ResourceManager.GetString("search_for_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук лекції.
        /// </summary>
        internal static string search_the_lesson {
            get {
                return ResourceManager.GetString("search_the_lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук предмету.
        /// </summary>
        internal static string search_the_subject {
            get {
                return ResourceManager.GetString("search_the_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти на сторінку.
        /// </summary>
        internal static string Slider_ToPage {
            get {
                return ResourceManager.GetString("Slider_ToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to реєстрації.
        /// </summary>
        internal static string Slider_ToRegister {
            get {
                return ResourceManager.GetString("Slider_ToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розпочати тестування.
        /// </summary>
        internal static string start_test {
            get {
                return ResourceManager.GetString("start_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус:.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватний.
        /// </summary>
        internal static string stat_private {
            get {
                return ResourceManager.GetString("stat_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей курс є приватним. Очікуйте затвердження підписки від викладача та оповіщення в особистих повідомленнях..
        /// </summary>
        internal static string stat_private_alert_subscrb {
            get {
                return ResourceManager.GetString("stat_private_alert_subscrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальнодоступний.
        /// </summary>
        internal static string stat_public {
            get {
                return ResourceManager.GetString("stat_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви підписались на курс!\n\rПро терміни здачі модуля Ви будете оповіщені по системі особистих повідомлень.\n\r\n\rЩоб відмінити підписку натисніть &quot;Відмінити&quot;.
        /// </summary>
        internal static string stat_public_alert_subscrb {
            get {
                return ResourceManager.GetString("stat_public_alert_subscrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підписатись.
        /// </summary>
        internal static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач:.
        /// </summary>
        internal static string teacher {
            get {
                return ResourceManager.GetString("teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очікуємо підтвердження.
        /// </summary>
        internal static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмети.
        /// </summary>
        internal static string _HorizontalNavigation_Courses {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навчання.
        /// </summary>
        internal static string _HorizontalNavigation_Education {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        internal static string _HorizontalNavigation_HomePage {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        internal static string _HorizontalNavigation_News {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль.
        /// </summary>
        internal static string _HorizontalNavigation_Profile {
            get {
                return ResourceManager.GetString("_HorizontalNavigation_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        internal static string _LogOnPartial_Exit {
            get {
                return ResourceManager.GetString("_LogOnPartial_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привіт,.
        /// </summary>
        internal static string _LogOnPartial_Hello {
            get {
                return ResourceManager.GetString("_LogOnPartial_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string _LogOnPartial_Register {
            get {
                return ResourceManager.GetString("_LogOnPartial_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввійти.
        /// </summary>
        internal static string _LogOnPartial_SignIn {
            get {
                return ResourceManager.GetString("_LogOnPartial_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нових повідомлень: .
        /// </summary>
        internal static string _NewMessageBox_NewMesseges {
            get {
                return ResourceManager.GetString("_NewMessageBox_NewMesseges", resourceCulture);
            }
        }
    }
}
