//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Metadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Metadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Metadata", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповідь:.
        /// </summary>
        public static string A_Answer {
            get {
                return ResourceManager.GetString("A_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть відповідь.
        /// </summary>
        public static string A_Answer_Required {
            get {
                return ResourceManager.GetString("A_Answer_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповідь повинна мати менше 128 символів.
        /// </summary>
        public static string A_Answer_StringLength {
            get {
                return ResourceManager.GetString("A_Answer_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правильно:.
        /// </summary>
        public static string A_Valid {
            get {
                return ResourceManager.GetString("A_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICQ:.
        /// </summary>
        public static string Contact_ICQ {
            get {
                return ResourceManager.GetString("Contact_ICQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер ICQ повинен мати менше 15 символів.
        /// </summary>
        public static string Contact_ICQ_StringLength {
            get {
                return ResourceManager.GetString("Contact_ICQ_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші контактні дані:.
        /// </summary>
        public static string Contact_Other {
            get {
                return ResourceManager.GetString("Contact_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактні дані повинні мати менше 120 символів.
        /// </summary>
        public static string Contact_Other_StringLength {
            get {
                return ResourceManager.GetString("Contact_Other_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скайп:.
        /// </summary>
        public static string Contact_Skype {
            get {
                return ResourceManager.GetString("Contact_Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скайп повинен мати менше 50 символів.
        /// </summary>
        public static string Contact_Skype_StringLength {
            get {
                return ResourceManager.GetString("Contact_Skype_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон:.
        /// </summary>
        public static string Contact_Tel {
            get {
                return ResourceManager.GetString("Contact_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон повинен мати менше 15 символів.
        /// </summary>
        public static string Contact_Tel_StringLength {
            get {
                return ResourceManager.GetString("Contact_Tel_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коротко про курс:.
        /// </summary>
        public static string Co_Desc {
            get {
                return ResourceManager.GetString("Co_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коротка інформація про курс обмежена 512 символами.
        /// </summary>
        public static string Co_Desc_StringLength {
            get {
                return ResourceManager.GetString("Co_Desc_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва курсу:.
        /// </summary>
        public static string Co_Title {
            get {
                return ResourceManager.GetString("Co_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва категорії:.
        /// </summary>
        public static string C_Title {
            get {
                return ResourceManager.GetString("C_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву.
        /// </summary>
        public static string C_Title_Required {
            get {
                return ResourceManager.GetString("C_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва обмежена 64 символами.
        /// </summary>
        public static string C_Title_StringLength {
            get {
                return ResourceManager.GetString("C_Title_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про себе:.
        /// </summary>
        public static string Information_About {
            get {
                return ResourceManager.GetString("Information_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле додаткової інформації обмежено 256 символами.
        /// </summary>
        public static string Information_About_StringLength {
            get {
                return ResourceManager.GetString("Information_About_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження:.
        /// </summary>
        public static string Information_DateOfBirth {
            get {
                return ResourceManager.GetString("Information_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я:.
        /// </summary>
        public static string Information_FirstName {
            get {
                return ResourceManager.GetString("Information_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ім&apos;я.
        /// </summary>
        public static string Information_FirstName_Required {
            get {
                return ResourceManager.GetString("Information_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я повинно мати менше 50 символів.
        /// </summary>
        public static string Information_FirstName_StringLength {
            get {
                return ResourceManager.GetString("Information_FirstName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище:.
        /// </summary>
        public static string Information_LastName {
            get {
                return ResourceManager.GetString("Information_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть прізвище.
        /// </summary>
        public static string Information_LastName_Required {
            get {
                return ResourceManager.GetString("Information_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище повинно мати менше 50 символів.
        /// </summary>
        public static string Information_LastName_StringLength {
            get {
                return ResourceManager.GetString("Information_LastName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По-батькові:.
        /// </summary>
        public static string Information_MidName {
            get {
                return ResourceManager.GetString("Information_MidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть по-батькові.
        /// </summary>
        public static string Information_MidName_Required {
            get {
                return ResourceManager.GetString("Information_MidName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По-батькові повинно мати менше 50 символів.
        /// </summary>
        public static string Information_MidName_StringLength {
            get {
                return ResourceManager.GetString("Information_MidName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затверджено:.
        /// </summary>
        public static string L_Accepted {
            get {
                return ResourceManager.GetString("L_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор:.
        /// </summary>
        public static string L_Author {
            get {
                return ResourceManager.GetString("L_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис лекції:.
        /// </summary>
        public static string L_Desc {
            get {
                return ResourceManager.GetString("L_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис лекції обмежений 50 символами.
        /// </summary>
        public static string L_Desc_StringLength {
            get {
                return ResourceManager.GetString("L_Desc_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва лекції:.
        /// </summary>
        public static string L_Title {
            get {
                return ResourceManager.GetString("L_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата завершення тестування:.
        /// </summary>
        public static string Mod_End {
            get {
                return ResourceManager.GetString("Mod_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть дату завершення тестування.
        /// </summary>
        public static string Mod_End_Required {
            get {
                return ResourceManager.GetString("Mod_End_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість балів за модуль:.
        /// </summary>
        public static string Mod_MaxPoints {
            get {
                return ResourceManager.GetString("Mod_MaxPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть кількість балів за модуль.
        /// </summary>
        public static string Mod_MaxPoints_Required {
            get {
                return ResourceManager.GetString("Mod_MaxPoints_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість запитань:.
        /// </summary>
        public static string Mod_QCount {
            get {
                return ResourceManager.GetString("Mod_QCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата початку тестування:.
        /// </summary>
        public static string Mod_Start {
            get {
                return ResourceManager.GetString("Mod_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть дату початку тестування.
        /// </summary>
        public static string Mod_Start_Required {
            get {
                return ResourceManager.GetString("Mod_Start_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час на здачу модуля (хвилин):.
        /// </summary>
        public static string Mod_Time {
            get {
                return ResourceManager.GetString("Mod_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потрібно вказати час на здачу модуля.
        /// </summary>
        public static string Mod_Time_Required {
            get {
                return ResourceManager.GetString("Mod_Time_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль:.
        /// </summary>
        public static string Mod_Title {
            get {
                return ResourceManager.GetString("Mod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва модуля обмежена 256 символами.
        /// </summary>
        public static string Mod_Title_StringLength {
            get {
                return ResourceManager.GetString("Mod_Title_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення:.
        /// </summary>
        public static string M_Mes {
            get {
                return ResourceManager.GetString("M_Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть повідомлення.
        /// </summary>
        public static string M_Mes_Required {
            get {
                return ResourceManager.GetString("M_Mes_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема:.
        /// </summary>
        public static string M_Title {
            get {
                return ResourceManager.GetString("M_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви забули ввести тему повідомлення.
        /// </summary>
        public static string M_Title_Required {
            get {
                return ResourceManager.GetString("M_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому:.
        /// </summary>
        public static string M_ToUser {
            get {
                return ResourceManager.GetString("M_ToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата публікації:.
        /// </summary>
        public static string N_Publication {
            get {
                return ResourceManager.GetString("N_Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст новини:.
        /// </summary>
        public static string N_Text {
            get {
                return ResourceManager.GetString("N_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть текст новини.
        /// </summary>
        public static string N_Text_Required {
            get {
                return ResourceManager.GetString("N_Text_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок:.
        /// </summary>
        public static string N_Title {
            get {
                return ResourceManager.GetString("N_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть заголовок новини.
        /// </summary>
        public static string N_Title_Required {
            get {
                return ResourceManager.GetString("N_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус:.
        /// </summary>
        public static string R_Role {
            get {
                return ResourceManager.GetString("R_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запитання:.
        /// </summary>
        public static string T_Question {
            get {
                return ResourceManager.GetString("T_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть запитання.
        /// </summary>
        public static string T_Question_Required {
            get {
                return ResourceManager.GetString("T_Question_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запитання обмежене 256 символами.
        /// </summary>
        public static string T_Question_StringLength {
            get {
                return ResourceManager.GetString("T_Question_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час закінчення тестування.
        /// </summary>
        public static string UMod_End {
            get {
                return ResourceManager.GetString("UMod_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат здачі модуля:.
        /// </summary>
        public static string UMod_Passed {
            get {
                return ResourceManager.GetString("UMod_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час початку тестування.
        /// </summary>
        public static string UMod_Start {
            get {
                return ResourceManager.GetString("UMod_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активований:.
        /// </summary>
        public static string U_Actived {
            get {
                return ResourceManager.GetString("U_Actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокований:.
        /// </summary>
        public static string U_Banned {
            get {
                return ResourceManager.GetString("U_Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата реєстрації:.
        /// </summary>
        public static string U_CreatedData {
            get {
                return ResourceManager.GetString("U_CreatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна скринька:.
        /// </summary>
        public static string U_Email {
            get {
                return ResourceManager.GetString("U_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останній вхід:.
        /// </summary>
        public static string U_LastLogin {
            get {
                return ResourceManager.GetString("U_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін:.
        /// </summary>
        public static string U_Login {
            get {
                return ResourceManager.GetString("U_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальнодоступний:.
        /// </summary>
        public static string Сo_Subscrb {
            get {
                return ResourceManager.GetString("Сo_Subscrb", resourceCulture);
            }
        }
    }
}
